

version: 0.2

env:
  variables:
    REGION: "us-east-1"
    ENVIRONMENT: "development"
    SERVICE_NAME: "lambda-transformer-nir"
    ERC: "149501088887.dkr.ecr.us-east-1.amazonaws.com"
    TAG: "dev"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 149501088887.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo ***** AMBIENTE ******
      - echo $ENVIRONMENT
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls
      - mkdir model
      - pip3 install sentence-transformers
      - python modeldownload.py
      - docker build -t lambda-transformer-nir .
      - docker push 149501088887.dkr.ecr.us-east-1.amazonaws.com/lambda-transformer-nir:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR/$SERVICE_NAME:$TAG